<?xml version='1.0' encoding='utf-8'?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
        <groupId>cn.dev33</groupId>
        <artifactId>sa-token-parent</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <packaging>jar</packaging>

	<name>sa-token-core</name>
    <artifactId>sa-token-core</artifactId>
	<description>An open-source, free, and one-stop Java authentication framework that makes authentication simple and elegant!</description>

	<dependencies>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<executions>
					<execution>
						<id>compile-coverage-summary</id>
						<phase>generate-test-sources</phase>
						<goals>
							<goal>compile</goal>
						</goals>
						<configuration>
							<compileSourceRoots>
								<compileSourceRoot>${project.basedir}/../sa-token-testing/sa-token-coverage/src/coverage-summary/java</compileSourceRoot>
							</compileSourceRoots>
							<outputDirectory>${project.build.directory}/coverage-summary-classes</outputDirectory>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<version>3.4.2</version>
				<executions>
					<execution>
						<goals>
							<goal>test-jar</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.jacoco</groupId>
				<artifactId>jacoco-maven-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>exec-maven-plugin</artifactId>
				<executions>
					<execution>
						<id>jacoco-coverage-summary</id>
						<phase>test</phase>
						<goals>
							<goal>java</goal>
						</goals>
						<configuration>
							<mainClass>${coverage.summary.mainClass}</mainClass>
							<additionalClasspathElements>
								<additionalClasspathElement>${project.build.directory}/coverage-summary-classes</additionalClasspathElement>
							</additionalClasspathElements>
							<arguments>
								<argument>${project.build.directory}/site/jacoco/jacoco.csv</argument>
								<argument>${project.build.directory}/site/jacoco/coverage-summary.html</argument>
								<argument>sa-token-core Coverage</argument>
								<argument>index.html</argument>
							</arguments>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>



</project>
