<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>cn.dev33</groupId>
		<artifactId>sa-token-parent</artifactId>
		<version>${revision}</version>
		<relativePath>../../pom.xml</relativePath>
	</parent>
	<artifactId>sa-token-u2f</artifactId>

	<name>${project.artifactId}</name>
	<description>sa-token-u2f</description>

	<dependencies>

		<!-- sa-token-core -->
		<dependency>
			<groupId>cn.dev33</groupId>
			<artifactId>sa-token-core</artifactId>
			<version>${revision}</version>
		</dependency>

		<!-- WebAuthn4J -->
		<dependency>
			<groupId>com.webauthn4j</groupId>
			<artifactId>webauthn4j-core</artifactId>
			<version>0.22.2.RELEASE</version>
		</dependency>

	</dependencies>

</project>
