<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>cn.dev33</groupId>
        <artifactId>sa-token-plugin</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <packaging>jar</packaging>

    <name>sa-token-reactive-redis-template</name>
    <artifactId>sa-token-reactive-redis-template</artifactId>
    <description>sa-token integrate ReactiveRedisTemplate</description>

    <dependencies>
        <!-- sa-token-spring-boot-starter -->
        <dependency>
            <groupId>cn.dev33</groupId>
            <artifactId>sa-token-core</artifactId>
        </dependency>
        <!-- spring-boot-starter-data-redis-reactive -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis-reactive</artifactId>
            <version>4.0.3</version>
        </dependency>
    </dependencies>

</project>