# 端口
server:
    port: 8099

# sa-token 配置
sa-token:
    token-name: satoken
    timeout: 2592000
    active-timeout: -1
    is-concurrent: true
    is-share: false
    token-style: uuid
    is-log: true
