import type { DefaultTheme } from 'vitepress'

/**
 * 左侧目录数据。改侧栏直接改本文件。
 */
export const sidebar: DefaultTheme.Sidebar = [
  {
    "text": "开始",
    collapsed: false,
    "items": [
      { "text": "框架介绍",                  "link": "/readme.html" },
      // { "text": "最新版本",                  "link": "/start/new-version.html" },
      { "text": "在 SpringBoot 环境集成",    "link": "/start/example.html" },
      { "text": "在 WebFlux 环境集成",       "link": "/start/webflux-example.html" },
      { "text": "在 Solon 环境集成",         "link": "/start/solon-example.html" },
      { "text": "其它环境集成示例",          "link": "/start/download.html" },
      { "text": "源码运行指南",              "link": "/start/run-source-code.html" },
      // { "text": "Maven 依赖拉取失败",        "link": "/start/maven-pull.html" },
      { "text": "Sa-Token 集成示例大全下载", "link": "/more/download-demos.html" },
    ]
  },
  {
    "text": "基础",
    collapsed: false,
    "items": [
      { "text": "登录认证",     "link": "/use/login-auth.html" },
      { "text": "权限认证",     "link": "/use/jur-auth.html" },
      { "text": "踢人下线",     "link": "/use/kick.html" },
      { "text": "注解鉴权",     "link": "/use/at-check.html" },
      { "text": "路由拦截鉴权", "link": "/use/route-check.html" },
      { "text": "Session会话",  "link": "/use/session.html" },
      { "text": "框架配置",     "link": "/use/config.html" },
    ]
  },
  {
    "text": "深入",
    collapsed: false,
    "items": [
      { "text": "集成 Redis",             "link": "/up/integ-redis.html" },
      { "text": "前后端分离",             "link": "/up/not-cookie.html" },
      { "text": "自定义 Token 风格",      "link": "/up/token-style.html" },
      { "text": "Token 提交前缀",         "link": "/up/token-prefix.html" },
      { "text": "同端互斥登录",           "link": "/up/mutex-login.html" },
      { "text": "记住我模式",             "link": "/up/remember-me.html" },
      { "text": "登录参数 & 注销参数",    "link": "/up/login-parameter.html" },
      { "text": "二级认证",               "link": "/up/safe-auth.html" },
      { "text": "模拟他人 & 身份切换",    "link": "/up/mock-person.html" },
      { "text": "账号封禁",               "link": "/up/disable.html" },
      { "text": "密码加密",               "link": "/up/password-secure.html" },
      { "text": "会话查询",               "link": "/up/search-session.html" },
      { "text": "Http Basic/Digest 认证", "link": "/up/basic-auth.html" },
      { "text": "全局侦听器",             "link": "/up/global-listener.html" },
      { "text": "全局过滤器",             "link": "/up/global-filter.html" },
      { "text": "多账号认证",             "link": "/up/many-account.html" },
    ]
  },
  {
    "text": "单点登录",
    collapsed: false,
    "items": [
      { "text": "单点登录简述",                     "link": "/sso/readme.html" },
      { "text": "搭建统一认证中心：SSO-Server",     "link": "/sso/sso-server.html" },
      { "text": "SSO-Server 认证中心开放 API 接口", "link": "/sso/sso-apidoc.html" },
      { "text": "SSO模式一 共享Cookie同步会话",     "link": "/sso/sso-type1.html" },
      { "text": "SSO模式二 URL重定向传播会话",      "link": "/sso/sso-type2.html" },
      { "text": "SSO模式三 Http请求获取会话",       "link": "/sso/sso-type3.html" },
      { "text": "配置域名校验",                     "link": "/sso/sso-check-domain.html" },
      { "text": "定制化登录页面",                   "link": "/sso/sso-custom-login.html" },
      { "text": "自定义API路由",                    "link": "/sso/sso-custom-api.html" },
      { "text": "平台中心跳转模式",                 "link": "/sso/sso-home-jump.html" },
      { "text": "匿名 client 接入",                 "link": "/sso/anon-client.html" },
      { "text": "单点注销",                         "link": "/sso/signout.html" },
      { "text": "前后端分离下的整合方案",           "link": "/sso/sso-h5.html" },
      { "text": "消息推送机制",                     "link": "/sso/message-push.html" },
      { "text": "用户数据同步 / 迁移",              "link": "/sso/user-data-sync.html" },
      { "text": "NoSdk、ReSdk 模式与非 java 项目",  "link": "/sso/sso-nosdk.html" },
      { "text": "SSO 代码 API 参考",                "link": "/sso/sso-dev.html" },
      // { "text": "不同 Client 不同秘钥",             "link": "/sso/sso-diff-key.html" },
      { "text": "常见问题总结",                     "link": "/sso/sso-questions.html" },
      { "text": "Sa-Pro：单点登录商业版",           "link": "https://sa-max.cn?way=st_sso" },
    ]
  },
  {
    "text": "OAuth2.0",
    collapsed: false,
    "items": [
      { "text": "OAuth2.0简述",                  "link": "/oauth2/readme.html" },
      { "text": "OAuth2-Server搭建",             "link": "/oauth2/oauth2-server.html" },
      { "text": "OAuth2-Server端开放 API 接口",  "link": "/oauth2/oauth2-apidoc.html" },
      { "text": "自定义数据加载器",              "link": "/oauth2/oauth2-data-loader.html" },
      { "text": "配置 client 域名校验",          "link": "/oauth2/oauth2-check-domain.html" },
      { "text": "自定义 Scope 权限及处理器",     "link": "/oauth2/oauth2-custom-scope.html" },
      { "text": "为 Scope 划分等级",             "link": "/oauth2/oauth2-scope-level.html" },
      { "text": "自定义 grant_type",             "link": "/oauth2/oauth2-custom-grant_type.html" },
      { "text": "定制化登录页面与授权页面",      "link": "/oauth2/oauth2-custom-login.html" },
      { "text": "自定义 API 路由",               "link": "/oauth2/oauth2-custom-api.html" },
      { "text": "OAuth2-Server端前后台分离",     "link": "/oauth2/oauth2-h5.html" },
      { "text": "OpenId 与 UnionId",             "link": "/oauth2/oauth2-openid.html" },
      { "text": "开启 OIDC 协议",                "link": "/oauth2/oauth2-oidc.html" },
      { "text": "使用注解校验 Access-Token",     "link": "/oauth2/oauth2-at-check.html" },
      { "text": "OAuth2-与登录会话实现数据互通", "link": "/oauth2/oauth2-interworking.html" },
      { "text": "OAuth2 代码 API 参考",          "link": "/oauth2/oauth2-dev.html" },
      { "text": "常见问题总结",                  "link": "/oauth2/oauth2-questions.html" },
      { "text": "Sa-Max：统一认证商业版",        "link": "https://sa-max.cn?way=st_oauth2" },
    ]
  },
  {
    "text": "微服务",
    collapsed: false,
    "items": [
      { "text": "分布式Session会话", "link": "/micro/dcs-session.html" },
      { "text": "网关统一鉴权",      "link": "/micro/gateway-auth.html" },
      { "text": "内部服务外网隔离",  "link": "/micro/same-token.html" },
      { "text": "依赖引入说明",      "link": "/micro/import-intro.html" },
    ]
  },
  {
    "text": "插件",
    collapsed: false,
    "items": [
      { "text": "AOP注解鉴权",                "link": "/plugin/aop-at.html" },
      { "text": "临时 Token 认证",            "link": "/plugin/temp-token.html" },
      { "text": "Quick-Login快速登录插件",    "link": "/plugin/quick-login.html" },
      { "text": "Alone独立Redis插件",         "link": "/plugin/alone-redis.html" },
      { "text": "Alone独立Redisson插件",      "link": "/plugin/alone-redisson.html" },
      { "text": "缓存层扩展",                 "link": "/plugin/dao-extend.html" },
      { "text": "JSON 序列化扩展",            "link": "/plugin/json-extend.html" },
      { "text": "序列化插件扩展包",           "link": "/plugin/custom-serializer.html" },
      { "text": "HTTP 请求扩展",              "link": "/plugin/http-extend.html" },
      { "text": "和 Thymeleaf 集成",          "link": "/plugin/thymeleaf-extend.html" },
      { "text": "和 Freemarker 集成",         "link": "/plugin/freemarker-extend.html" },
      { "text": "注解鉴权 SpEL 表达式",       "link": "/plugin/spel-at.html" },
      { "text": "和 jwt 集成",                "link": "/plugin/jwt-extend.html" },
      { "text": "和 Dubbo 集成",              "link": "/plugin/dubbo-extend.html" },
      { "text": "和 gRPC 集成",               "link": "/plugin/grpc-extend.html" },
      { "text": "API 接口参数签名",           "link": "/plugin/api-sign.html" },
      { "text": "API Key 接口调用秘钥",       "link": "/plugin/api-key.html" },
      { "text": "Sa-Token 插件开发指南",      "link": "/fun/plugin-dev.html" },
      { "text": "自定义 SaTokenContext 指南", "link": "/fun/sa-token-context.html" },
    ]
  },
  {
    "text": "API手册",
    collapsed: false,
    "items": [
      { "text": "StpUtil-鉴权工具类",      "link": "/api/stp-util.html" },
      { "text": "SaSession-会话对象",      "link": "/api/sa-session.html" },
      { "text": "SaTokenDao-数据持久接口", "link": "/api/sa-token-dao.html" },
      { "text": "SaStrategy-全局策略",     "link": "/api/sa-strategy.html" },
      { "text": "全局类、方法",            "link": "/more/common-action.html" },
    ]
  },
  {
    "text": "框架设计",
    collapsed: false,
    "items": [
      { "text": "仓库目录", "link": "/arch/dir-intro.html" },
      { "text": "数据结构", "link": "/arch/data-structure.html" },
    ]
  },
  {
    "text": "其它",
    collapsed: false,
    "items": [
      { "text": "更新日志",            "link": "/more/update-log.html" },
      { "text": "框架生态",            "link": "/more/link.html" },
      { "text": "框架博客",            "link": "/more/blog.html" },
      // { "text": "推荐阅读",            "link": "/more/recommended.html" },
      { "text": "推荐公众号",          "link": "/more/tj-gzh.html" },
      // { "text": "公众号合作",          "link": "/more/tj-gzh-hz.html" },
      { "text": "加入讨论群",          "link": "/more/join-group.html" },
      { "text": "Sa-Token 内容合作群", "link": "/more/content-cooperation.html" },
      { "text": "赞助 Sa-Token",       "link": "/more/sa-token-donate.html" },
      { "text": "需求提交",            "link": "/more/demand-commit.html" },
      { "text": "问卷调查",            "link": "/more/wenjuan.html" },
    ]
  },
  {
    "text": "附录",
    collapsed: false,
    "items": [
      { "text": "常见问题排查",                       "link": "/more/common-questions.html" },
      { "text": "框架名词解释",                       "link": "/more/noun-intro.html" },
      { "text": "Sa-Token功能结构图",                 "link": "/fun/auth-flow.html" },
      { "text": "全局 Log 输出",                      "link": "/fun/log.html" },
      { "text": "异步 & Mock 上下文",                 "link": "/fun/async--mock.html" },
      { "text": "未登录场景值详解",                   "link": "/fun/not-login-scene.html" },
      { "text": "Token有效期详解",                    "link": "/fun/token-timeout.html" },
      { "text": "Session模型详解",                    "link": "/fun/session-model.html" },
      { "text": "数据读写三大作用域",                 "link": "/fun/three-scope.html" },
      { "text": "TokenInfo参数详解",                  "link": "/fun/token-info.html" },
      { "text": "异常细分状态码",                     "link": "/fun/exception-code.html" },
      { "text": "自定义注解",                         "link": "/fun/custom-annotations.html" },
      { "text": "防火墙",                             "link": "/fun/firewall.html" },
      { "text": "参考：把权限放在缓存里",             "link": "/fun/jur-cache.html" },
      { "text": "参考：把路由拦截鉴权动态化",         "link": "/fun/dynamic-router-check.html" },
      { "text": "解决反向代理 uri 丢失的问题",        "link": "/fun/curr-domain.html" },
      { "text": "解决跨域问题",                       "link": "/fun/cors-filter.html" },
      { "text": "技术选型：SSO 与 OAuth2 对比",       "link": "/fun/sso-vs-oauth2.html" },
      { "text": "集成 MongoDB 参考一",                "link": "/up/integ-spring-mongod-1.html" },
      { "text": "集成 MongoDB 参考二",                "link": "/up/integ-spring-mongod-2.html" },
      { "text": "从 Shiro、SpringSecurity、JWT 迁移", "link": "/fun/auth-framework-function-test.html" },
      { "text": "issue 提问模板",                     "link": "/fun/issue-template.html" },
      { "text": "为Sa-Token贡献代码",                 "link": "/fun/git-pr.html" },
      { "text": "Sa-Token开源大事记",                 "link": "/fun/timeline.html" },
      { "text": "团队成员",                           "link": "/fun/team.html" },
      // { "text": "框架源码技术栈",                     "link": "/fun/tech-stack.html" },
      // { "text": "参考资料",                           "link": "/fun/refer-info.html" },
      { "text": "Sa-Token框架掌握度--在线考试",       "link": "/fun/sa-token-test.html" },
    ]
  },
]
